apiVersion : apps/v1
kind: Deployment
metadata:
 name: producerdeployment
 labels:
  app: producerdeployment
spec:
 replicas: 1
 selector:
  matchLabels:
   app: producer
 template:
  metadata:
   labels:
    app: producer
  spec:
   containers:
     - image: arshabbir/producer
       name : producer
       imagePullPolicy: Always
       env:
        - name: TRAFFIC_INTERVAL
          value : "30"
        - name: KAFKA_HOST 
          value : "172.31.38.67:29092"
        - name: TOPIC 
          value : "myTopic1"
    



---
apiVersion: v1
kind: Service
metadata:
  name: producer-service
spec:
  type: NodePort
  selector:
    app: producer
  ports:
    
    - port: 8082
      targetPort: 8082
      nodePort: 30008